### ISSUE TITLE
Cannot install it from pip in windows!

### ISSUE THREAD

**Issue by klarkxy** [nppoly/cyac#11]
```pwsh
pip install cyac
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting cyac
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/db/2e/4a4916514b64694dd478ab085f01fb4ca599e3127c05704f98f3067e8fc7/cyac-1.3.tar.gz (38 kB)  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>     
        File "<pip-setuptools-caller>", line 34, 
in <module>
        File "C:\Users\admin\AppData\Local\Temp\pip-install-h1651_cj\cyac_4973446135a546ce84624d967d791583\setup.py", line 10, in <module>
          long_description = open("README.md").read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 3452: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, 
and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
python version:   Python 3.10.1
pip version:  pip 22.0.4

**Comment by klarkxy** [comment]
I clone the code, and change `long_description = open("README.md").read()` to `long_description = open("README.md", encoding="utf8").read()`, it worked.

**Comment by chenkovsky** [comment]
issue was fixed in https://github.com/nppoly/cyac/pull/12
